export enum Race {
  CHALACTEENS, CHISS, HUMAINS, ITHORIENS, MIRIALANS, KELDOR,
  KIFFARS, MIRALUKAS, NAGAIS, NEIMOIDIENS, NIKTOS, NOGHRIS,
  ONGREES, PAUANS, QUERMIENS, RAKATA, RODIENS, THISSPASIENS,
  TOGRUTAS, WOOKIES, WRONIANS, ZABRAKS
}
