export enum Race {
  CHALACTEEN, CHIS, HUMAIN, ITHORIEN, MIRIALAN, KELDOR,
  KIFFAR, MIRALUKA, NAGAI, NEIMOIDIEN, NIKTO, NOGHRI,
  ONGREE, PAUAN, QUERMIEN, RAKATA, RODIEN, THISSPASIEN,
  TOGRUTA, WOOKIE, WRONIAN, ZABRAK
}
